# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - samulin-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://samulinacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a6d9dec14ee34dd9a14c23880960702e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2dc3849ce66f4c1398d56e68d5b3648c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: samulinacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a6d9dec14ee34dd9a14c23880960702e }}/samulin-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'samulin-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b3f96a3df97148c6a144e0b82b7ea822 }}
        images: 'samulinacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a6d9dec14ee34dd9a14c23880960702e }}/samulin-server:${{ github.sha }}'